/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pertemuan5;

import Pertemuan4.*;
import java.awt.Image;
import java.awt.Rectangle;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Bukhori
 */
public class KTP1 extends javax.swing.JFrame {

    /**
     * Creates new form KTP
     */
    public KTP1() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tampilnik = new javax.swing.JTextField();
        tampilnama = new javax.swing.JTextField();
        tampiltgl = new javax.swing.JTextField();
        tampilalamat = new javax.swing.JTextField();
        tampilrtrw = new javax.swing.JTextField();
        tampildesa = new javax.swing.JTextField();
        tampilkecamatan = new javax.swing.JTextField();
        tampilagama = new javax.swing.JTextField();
        tampilstatusperkawinan = new javax.swing.JTextField();
        tampilpekerjaan = new javax.swing.JTextField();
        tampilkewarganegaraan = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        pathfoto = new javax.swing.JTextField();
        tampilgambar = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        tombolcari = new javax.swing.JButton();
        TombolSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("PROVINSI JAWA TIMUR");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("KABUPATEN BLITAR");

        jLabel3.setText("NIK");

        jLabel4.setText("Nama");

        jLabel5.setText("Tempat/Tgl Lahir");

        jLabel6.setText("Alamat");

        jLabel7.setText("RT/RW");

        jLabel8.setText("Kel/Desa");

        jLabel9.setText("Kecamatan");

        jLabel10.setText("Agama");

        jLabel11.setText("Status Perkawinan");

        jLabel12.setText("Pekerjaan");

        jLabel13.setText("Kewarganegaraan");

        tampilstatusperkawinan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilstatusperkawinanActionPerformed(evt);
            }
        });

        jButton2.setText("Browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tampilgambar.setText(".");
        tampilgambar.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tampilstatusperkawinan)
                                    .addComponent(tampilagama)
                                    .addComponent(tampilalamat)
                                    .addComponent(tampilrtrw)
                                    .addComponent(tampildesa)
                                    .addComponent(tampilkecamatan)
                                    .addComponent(tampilnama)
                                    .addComponent(tampiltgl)
                                    .addComponent(tampilnik)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tampilpekerjaan)
                                    .addComponent(tampilkewarganegaraan)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(tampilgambar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(pathfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(87, 87, 87))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tampilnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tampilnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tampiltgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tampilalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tampilrtrw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tampilgambar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tampildesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tampilkecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tampilagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tampilstatusperkawinan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tampilpekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(tampilkewarganegaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(pathfoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tombolcari.setText("CARI");
        tombolcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolcariActionPerformed(evt);
            }
        });

        TombolSimpan.setText("SIMPAN");
        TombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(tombolcari, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TombolSimpan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolcari)
                    .addComponent(TombolSimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void show(String a) {
        String baris = null;

        // filereader adalah class, // objek
        FileReader namaobjek = null;
        try {
            namaobjek = new FileReader(a);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(KTP1.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Menampilkan file
        BufferedReader namaobjek2 = new BufferedReader(namaobjek);

        try {
            int bariske = 0;
            while ((baris = namaobjek2.readLine()) != null) {
                if (bariske == 0) {
                    tampilnik.setText(baris);
                } else if (bariske == 1) {
                    tampilnama.setText(baris);
                } else if (bariske == 2) {
                    tampiltgl.setText(baris);
                } else if (bariske == 3) {
                    tampilgambar.setIcon(new javax.swing.ImageIcon(getClass().getResource(baris)));
                    pathfoto.setText(baris);
                } else if (bariske == 4) {
                    tampilalamat.setText(baris);
                } else if (bariske == 5) {
                    tampilrtrw.setText(baris);
                } else if (bariske == 6) {
                    tampildesa.setText(baris);
                } else if (bariske == 7) {
                    tampilkecamatan.setText(baris);
                } else if (bariske == 8) {
                    tampilagama.setText(baris);
                } else if (bariske == 9) {
                    tampilstatusperkawinan.setText(baris);
                } else if (bariske == 10) {
                    tampilpekerjaan.setText(baris);
                } else if (bariske == 11) {
                    tampilkewarganegaraan.setText(baris);
                }
                bariske++;

            }
        } catch (IOException ex) {
            Logger.getLogger(KTP.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            namaobjek2.close();
        } catch (IOException ex) {
            Logger.getLogger(KTP1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void tombolcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolcariActionPerformed

        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser("");
        File filenya;

        int buka_dialog = chooser.showOpenDialog(KTP1.this);
        if (buka_dialog == JFileChooser.APPROVE_OPTION) {
            filenya = chooser.getSelectedFile();
            path.setText(filenya.getPath());

            // Read TXT File
            String filename = filenya.getPath(); //path
            show(filename);
        }
    }//GEN-LAST:event_tombolcariActionPerformed

    private void TombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolSimpanActionPerformed
        // TODO add your handling code here:

        File file = new File("D://input2.txt");
        file.delete();

        path.setText(file.getPath());
        String filename = file.getPath();

        try {
            FileWriter writer = new FileWriter("D://input2.txt", true);
            BufferedWriter bufferedWriter = new BufferedWriter(writer);
            bufferedWriter.write(tampilnik.getText());
            bufferedWriter.newLine();
            bufferedWriter.write(tampilnama.getText());
            bufferedWriter.newLine();
            bufferedWriter.write(tampiltgl.getText());
            bufferedWriter.newLine();
            bufferedWriter.write(pathfoto.getText());
            bufferedWriter.newLine();
            bufferedWriter.write(tampilalamat.getText());
            bufferedWriter.newLine();
            bufferedWriter.write(tampilrtrw.getText());
            bufferedWriter.newLine();
            bufferedWriter.write(tampildesa.getText());
            bufferedWriter.newLine();
            bufferedWriter.write(tampilkecamatan.getText());
            bufferedWriter.newLine();
            bufferedWriter.write(tampilagama.getText());
            bufferedWriter.newLine();
            bufferedWriter.write(tampilstatusperkawinan.getText());
            bufferedWriter.newLine();
            bufferedWriter.write(tampilpekerjaan.getText());
            bufferedWriter.newLine();
            bufferedWriter.write(tampilkewarganegaraan.getText());
            bufferedWriter.newLine();
            bufferedWriter.close();

            show(file.getPath());

        } catch (IOException e) {
        }

        /*JFileChooser chooser = new JFileChooser("");
        File filenya;

        int buka_dialog = chooser.showOpenDialog(KTP1.this);
        if (buka_dialog == JFileChooser.APPROVE_OPTION) {
            String filepath = String.valueOf(chooser.getSelectedFile().getPath());
            if (!filepath.endsWith(".txt")) {
                filepath = filepath + ".txt";
            }

            File file = new File(filepath);
            FileWriter fw = null;
            BufferedWriter bw = null;

            try {

                fw = new FileWriter(file);
                bw = new BufferedWriter(fw);

                String ambilnik = tampilnik.getText() + System.getProperty("line.separator");
                String ambilnama = tampilnama.getText() + System.getProperty("line.separator");
                String ambiltgl = tampiltgl.getText() + System.getProperty("line.separator");
                String ambilalamat = tampilalamat.getText() + System.getProperty("line.separator");
                String ambilrtrw = tampilrtrw.getText() + System.getProperty("line.separator");
                String ambildesa = tampildesa.getText() + System.getProperty("line.separator");
                String ambilkecamatan = tampilkecamatan.getText() + System.getProperty("line.separator");
                String ambilagama = tampilagama.getText() + System.getProperty("line.separator");
                String ambilstatus = tampilstatusperkawinan.getText() + System.getProperty("line.separator");
                String ambilpekerjaan = tampilpekerjaan.getText() + System.getProperty("line.separator");
                String ambilkewarganegaraan = tampilkewarganegaraan.getText() + System.getProperty("line.separator");

                bw.write(ambilnik);
                bw.write(ambilnama);
                bw.write(ambiltgl);
                bw.write(ambilalamat);
                bw.write(ambilrtrw);
                bw.write(ambildesa);
                bw.write(ambilkecamatan);
                bw.write(ambilagama);
                bw.write(ambilstatus);
                bw.write(ambilpekerjaan);
                bw.write(ambilkewarganegaraan);

            } catch (IOException e) {
            } finally {
                JOptionPane.showMessageDialog(null, "Berhasil Disimpan!");
                try {

                    bw.close();
                    fw.close();

                } catch (IOException e) {
                }
            }

        }*/
    }//GEN-LAST:event_TombolSimpanActionPerformed

    private void tampilstatusperkawinanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilstatusperkawinanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilstatusperkawinanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int res = chooser.showOpenDialog(KTP1.this);
        if (res == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            // mengambil gambar dari file yg dipilih
            ImageIcon gambar = new ImageIcon(file.getAbsolutePath());

            // atur lebar & tinggi pada jlabel14gg
            Rectangle rect = tampilgambar.getBounds();

            // set gambar agar pas pada jlabel14
            Image scaledimage = gambar.getImage().getScaledInstance(rect.width, rect.height, Image.SCALE_DEFAULT);

            // konversi file gambar agar bisa dibaca pada jlabel14
            gambar = new ImageIcon(scaledimage);
            tampilgambar.setIcon(gambar);

            // mnampilkan nama file foto
//            String name = file.getName();
//            jLabel2.setText(name);
        } else {
            JOptionPane.showMessageDialog(this, "Cancelled by user!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KTP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KTP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KTP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KTP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KTP1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TombolSimpan;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField path;
    private javax.swing.JTextField pathfoto;
    private javax.swing.JTextField tampilagama;
    private javax.swing.JTextField tampilalamat;
    private javax.swing.JTextField tampildesa;
    private javax.swing.JLabel tampilgambar;
    private javax.swing.JTextField tampilkecamatan;
    private javax.swing.JTextField tampilkewarganegaraan;
    private javax.swing.JTextField tampilnama;
    private javax.swing.JTextField tampilnik;
    private javax.swing.JTextField tampilpekerjaan;
    private javax.swing.JTextField tampilrtrw;
    private javax.swing.JTextField tampilstatusperkawinan;
    private javax.swing.JTextField tampiltgl;
    private javax.swing.JButton tombolcari;
    // End of variables declaration//GEN-END:variables

}
